TestWebApp/Models/EndorsementRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.IdentityModel.Tokens.Jwt;

namespace Frost.Models
{
    public enum EndorsementRequestStatus
    {
        New,
        Approved,
        Rejected
    }

    public class EndorsementRequest
    {
        public Guid? Id { get; set; }

        [Required(ErrorMessage = "Please enter a contact name.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter a valid email address.")]
        public string Email { get; set; }

        [Required(ErrorMessage="Please enter your organization's name.")]
        public string Organization { get; set; }

        public string LogoUri { get; set; }

        [Required(ErrorMessage="Please enter a uri for your application's OAuth2 entry point")]
        [Display(Name="Login Uri")]
        public string LoginUri { get; set; }

        [Required(ErrorMessage = "Please enter a uri for your application's OAuth2 JWT processing")]
        public List<string> RedirectUris { get; set; }

        [Required(ErrorMessage="Please enter a friendly name for your application")]
        public string Application { get; set; }

        [Display(Name ="Application URL")]
        [Required(ErrorMessage="Please enter a valid url for your application")]
        public string ApplicationUrl { get; set; }

        public EndorsementRequestStatus Status { get; set; }

        //public List<string> GrantTypes { get; set; }

        public JwtPayload ToPayload()
        {
            var payload = new JwtPayload();

            int issuedDate = (int)(DateTime.UtcNow
               .Subtract(new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc))
               .TotalMilliseconds);

            var expireDate = (int)(DateTime.UtcNow.AddYears(1).Subtract(new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalMilliseconds);

            payload["software_id"] = Id;
            payload["iss"] = "http://tempuri.org/poet";
            payload["iat"] = issuedDate;
            payload["exp"] = expireDate;
            payload["client_name"] = Application;
            payload["client_uri"] = ApplicationUrl;
            payload["logo_uri"] = LogoUri;
            payload["initiate_login_uri"] = LoginUri;
            payload["redirect_uris"] = $"[{string.Join(",", RedirectUris.Select(u => $"\"{u}\""))}]";
            payload["token_endpoint_auth_method"] = "client_secret_post";
            //payload["grant_types"] = $"[{string.Join(",", GrantTypes.Select(u => $"\"{u}\""))}]";

            return payload;
        }
    }
}

TestWebApp/Controllers/EndorsementRequestController.cs
using Frost.Models;
using System;
using System.IO;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

namespace Frost.Controllers
{
    public class EndorsementRequestController : Controller
    {       
        // GET: Request
        public ActionResult Index()
        {           
            EndorsementRequest req = new EndorsementRequest();
            return View(req);
        }

        // POST: Request/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EndorsementRequest request)
        {
            if (!ModelState.IsValid)
                return View("Index", request);

            request.Id = Guid.NewGuid();
            request.Status = EndorsementRequestStatus.New;

            try
            {
                EndorsementRequestCollection.Current.Add(request);
            }
            catch
            {
                ModelState.TryAddModelError("", "Error saving file");
                return View("Index", request);
            }

            return View("CreateSuccess");
        }

        // GET: Request/Delete/5
        public ActionResult Delete(int id)        {
            return View();
        }
    }
}

TestWebApp/Views/EndorsementRequest/CreateSuccess.cshtml
@{
    ViewBag.Title = "CreateSuccess";
}

<h2>Endorsement Request Result.</h2>

<div class="alert alert-success">Your Endorsement Request has been successfully submitted.</div>

TestWebApp/Views/EndorsementRequest/Index.cshtml
@model Frost.Models.EndorsementRequest

@{
    ViewBag.Title = "Create Endorsement Request";
}

<h2>Create Endorsement Request</h2>


@using (Html.BeginForm("Create","EndorsementRequest")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Contact Information</h3>
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @type = "email" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Organization, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Organization, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Organization, "", new { @class = "text-danger" })
            </div>
        </div>

        <h3>Application Information</h3>

        <div class="form-group">
            @Html.LabelFor(model => model.Application, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Application, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Application, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationUrl, "", new { @class = "text-danger", @type = "url" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoginUri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoginUri, new { htmlAttributes = new { @class = "form-control", @type = "url" } })
                @Html.ValidationMessageFor(model => model.LoginUri, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RedirectUris, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="url" name="RedirectUris" id="RedirectUris" class="form-control"/>
                @Html.ValidationMessageFor(model => model.RedirectUris, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}